/** Standalone Host UI. Role/cardinality metadata comes from APIs; no ontology path or prompt template is embedded here. */
export const PLAYGROUND_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="description" content="Compile declared visual references through VOCE"><title>VOCE Playground</title>
<style>
:root{color-scheme:light;--ink:#18212f;--muted:#5b6878;--line:#d7dee8;--panel:#fff;--wash:#f4f7fb;--accent:#3b5ccc;--danger:#9a2d2d}*{box-sizing:border-box}body{margin:0;font:16px/1.5 system-ui,-apple-system,Segoe UI,sans-serif;color:var(--ink);background:var(--wash)}main{max-width:1180px;margin:0 auto;padding:24px 16px 64px}h1{margin:0 0 4px;font-size:clamp(1.6rem,4vw,2.4rem)}h2{margin:0 0 12px;font-size:1.18rem}.lede{margin:0;color:var(--muted);max-width:75ch}.tabs{display:flex;gap:8px;margin:16px 0}.tab{border:1px solid var(--line);border-radius:999px;padding:9px 16px;background:var(--panel);cursor:pointer}.tab[aria-selected=true]{background:var(--accent);border-color:var(--accent);color:#fff}.layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.15fr);gap:16px;align-items:start}.panel{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px}.slot-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.slot{border:1px dashed #b8c3d2;border-radius:10px;padding:12px;background:#fbfcfe}.slot.required{border-style:solid}.slot label{display:block;font-weight:650;margin-bottom:6px}.hint{color:var(--muted);font-size:.86rem;margin:4px 0 8px}input,select,button{font:inherit}input[type=file],input[type=password],select{width:100%}input[type=password],select{border:1px solid var(--line);border-radius:8px;padding:9px;background:#fff}button.primary{border:0;border-radius:9px;padding:10px 15px;background:var(--accent);color:#fff;font-weight:700;cursor:pointer;margin-right:8px}button.primary:disabled{opacity:.55;cursor:not-allowed}.preview{display:none;width:100%;max-height:150px;object-fit:contain;margin-top:8px;border-radius:7px;background:#eef2f7}.preview.visible{display:block}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.check{display:flex;gap:8px;align-items:flex-start;margin:14px 0}.notice{border-left:4px solid #d39d26;background:#fff8e8;padding:10px 12px;color:#634b13;font-size:.9rem}.provider-controls{margin:12px 0;padding:12px;border:1px solid var(--line);border-radius:9px}.status{margin:12px 0;min-height:1.5em;color:var(--muted)}.status.error{color:var(--danger)}.result{min-width:0}.result pre{white-space:pre-wrap;overflow:auto;max-height:420px;margin:0;background:#101827;color:#e6edf7;border-radius:9px;padding:12px;font:12px/1.45 ui-monospace,SFMono-Regular,Consolas,monospace}.result-section{margin-top:12px}.result-section summary{cursor:pointer;font-weight:700;padding:8px 0}.badge{display:inline-block;padding:3px 8px;border-radius:999px;background:#e8edf8;color:#2a438f;font-size:.8rem}@media(max-width:760px){main{padding:18px 12px 48px}.layout{grid-template-columns:1fr}.slot-grid,.row{grid-template-columns:1fr}.panel{padding:13px}.tabs{overflow:auto}}@media(max-width:480px){button.primary{width:100%;margin:5px 0}.tabs{white-space:nowrap}}
</style></head><body><main>
<header><h1>VOCE Playground</h1><p class="lede">Upload declared references, choose a composition, inspect the compiled plan, and—only when an approved transport is enabled—make one confirmed generation call.</p></header>
<nav class="tabs" aria-label="Scenario"><button class="tab" type="button" data-scenario="virtual-tryon" aria-selected="true">Virtual Try-On</button><button class="tab" type="button" data-scenario="cosplay" aria-selected="false">Cosplay</button></nav>
<div class="layout"><section class="panel" aria-labelledby="input-title"><h2 id="input-title">References and composition</h2><div id="slots" class="slot-grid" aria-live="polite"></div><div id="supplemental"></div>
<div class="row"><div><label for="composition">Composition preset</label><select id="composition"><option value="">No preset</option></select></div><div><label for="provider">Provider profile</label><select id="provider"></select></div></div>
<p class="hint">Composition choices come from the public Core catalog. Provider choices come from the server allow-list.</p>
<div id="provider-controls" class="provider-controls" hidden><label for="byok">Provider API key</label><input id="byok" type="password" autocomplete="off" spellcheck="false" placeholder="Request-scoped; never stored"><p id="provider-note" class="hint"></p></div><label class="check"><input id="single-call" type="checkbox"><span>I approve exactly one Provider call at the displayed estimate (Mock costs zero).</span></label>
<label class="check"><input id="rights" type="checkbox"><span>I have the right to use these images. Compile stays local; Generate may send them to the selected Provider.</span></label>
<div class="notice" role="note">Pose reference guidance: upload a ready-made skeleton image, action photo, or pose sketch. No pose extraction or editor is included.</div>
<p><button id="compile" class="primary" type="button" disabled>Compile plan</button><button id="generate" class="primary" type="button" disabled>Generate once</button></p><p id="status" class="status" role="status" aria-live="polite"></p></section>
<section class="panel result" aria-labelledby="result-title"><h2 id="result-title">Result <span id="result-badge" class="badge">Waiting</span></h2><p class="hint">Observed facts and confirmed source bindings stay empty until an approved interpreter supplies evidence.</p><div id="result-body"><p class="status">Choose references, confirm rights, and compile.</p></div></section></div></main>
<script>
(()=>{const state={scenario:'virtual-tryon',meta:null,controls:new Map(),sessionId:crypto.randomUUID?crypto.randomUUID():String(Date.now()),compiled:null,compileInput:null},$=id=>document.getElementById(id),slots=$('slots'),supplemental=$('supplemental'),composition=$('composition'),provider=$('provider'),rights=$('rights'),compile=$('compile'),generate=$('generate'),byok=$('byok'),singleCall=$('single-call'),providerControls=$('provider-controls'),providerNote=$('provider-note'),status=$('status'),resultBody=$('result-body'),badge=$('result-badge');
const label=role=>role.replaceAll('-',' ').replace(/(^| )[a-z]/g,c=>c.toUpperCase()),roles=()=>((state.meta.scenarios.find(item=>item.id===state.scenario)||{}).roles||[]),selectedProvider=()=>state.meta.providers.find(item=>item.id===provider.value);
function invalidate(){state.compiled=null;state.compileInput=null;generate.disabled=true}
function addControl(role,required,index){const key=role+':'+index,wrap=document.createElement('div');wrap.className='slot'+(required?' required':'');const id='file-'+key.replace(/[^a-z0-9]+/gi,'-'),title=document.createElement('label');title.htmlFor=id;title.textContent=label(role)+(required?' (required)':' (optional)');const hint=document.createElement('p');hint.className='hint';hint.textContent=role==='pose'?'Skeleton image, action photo, or pose sketch.':'The slot role is validated by the selected ScenarioPack.';const input=document.createElement('input');input.type='file';input.id=id;input.accept='image/png,image/jpeg,image/webp';input.setAttribute('aria-label',title.textContent);const preview=document.createElement('img');preview.className='preview';preview.alt='';input.addEventListener('change',()=>{invalidate();const file=input.files&&input.files[0];if(!file)return;preview.src=URL.createObjectURL(file);preview.alt=label(role)+' local preview';preview.classList.add('visible')});wrap.append(title,hint,input,preview);slots.appendChild(wrap);state.controls.set(key,{role,input})}
function renderControls(){slots.replaceChildren();state.controls.clear();supplemental.replaceChildren();invalidate();for(const role of roles())for(let i=0;i<role.minCount;i++)addControl(role.role,true,i);const optional=roles().filter(role=>role.maxCount>role.minCount);if(optional.length){const title=document.createElement('h3');title.textContent='Supplemental references';const select=document.createElement('select');select.setAttribute('aria-label','Supplemental reference role');for(const role of optional)select.appendChild(new Option(label(role.role),role.role));const add=document.createElement('button');add.type='button';add.className='primary';add.style.marginTop='8px';add.textContent='Add supplemental';const counts={};add.addEventListener('click',()=>{const role=select.value,count=counts[role]||0,policy=optional.find(item=>item.role===role);if(!policy||count>=policy.maxCount-policy.minCount)return;counts[role]=count+1;addControl(role,false,policy.minCount+count)});supplemental.append(title,select,add)}}
function renderProvider(){const item=selectedProvider();if(!item)return;const needsKey=item.credentialMode==='user_ephemeral';providerControls.hidden=!needsKey;byok.required=needsKey;providerNote.textContent=(item.transportEnabled?'Transport enabled. ':'Transport disabled. ')+(item.pricePerImage||0)+' '+item.currency+' headline output price; the compiled result shows the request estimate.';invalidate()}
function renderMeta(){composition.replaceChildren(new Option('No preset',''));for(const item of state.meta.presets)composition.appendChild(new Option(item.id.replaceAll('-',' '),item.id));provider.replaceChildren();for(const item of state.meta.providers)provider.appendChild(new Option(item.label+(item.transportEnabled?'':' (transport off)'),item.id));renderControls();renderProvider()}
async function upload(file,role){const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));const response=await fetch('/api/upload',{method:'POST',headers:{'content-type':'application/json','x-playground-session':state.sessionId},body:JSON.stringify({fileName:file.name,mediaType:file.type,bytesBase64:btoa(binary),role,poseSourceKind:role==='pose'?'pose-sketch':undefined})});const value=await response.json();if(!response.ok)throw new Error(value.error||'Upload failed');return value}
function showResult(value,title){badge.textContent=title;resultBody.replaceChildren();for(const pair of [['Provider capability',value.providerCapability],['Human Plan',value.humanPlan],['Constraints',value.constraintIR],['Prompt IR',value.promptIR],['Trace',value.trace],['Provider request',value.providerRenderRequest]]){if(pair[1]===undefined)continue;const details=document.createElement('details');details.className='result-section';details.open=pair[0]==='Provider capability'||pair[0]==='Human Plan';const summary=document.createElement('summary');summary.textContent=pair[0];const pre=document.createElement('pre');pre.textContent=JSON.stringify(pair[1],null,2);details.append(summary,pre);resultBody.append(details)}}
async function runCompile(){status.className='status';status.textContent='Uploading references and compiling…';compile.disabled=true;invalidate();try{const assets=[],declaredRoles=[];for(const control of state.controls.values()){const file=control.input.files&&control.input.files[0];if(!file)continue;const uploaded=await upload(file,control.role);assets.push(uploaded.artifact);declaredRoles.push({assetId:uploaded.artifact.id,role:control.role,order:0})}state.compileInput={scenarioId:state.scenario,assets,declaredRoles,compositionSelections:composition.value?[{presetId:composition.value}]:[],providerProfileId:provider.value,rightsConfirmed:rights.checked};const response=await fetch('/api/compile',{method:'POST',headers:{'content-type':'application/json','x-playground-session':state.sessionId},body:JSON.stringify(state.compileInput)});const value=await response.json();if(!response.ok)throw new Error(value.error||'Compilation failed');state.compiled=value;showResult(value,'Compiled');const item=selectedProvider();generate.disabled=!(state.meta.renderEnabled&&item&&item.transportEnabled&&value.providerCapability.status==='ok');status.textContent=value.providerCapability.status==='ok'?'Plan compiled. The selected Provider can accept this plan.':'Plan compiled, but Generate is blocked: '+value.providerCapability.reasons.join(', ')}catch(error){badge.textContent='Blocked';resultBody.replaceChildren();status.className='status error';status.textContent=error instanceof Error?error.message:'Compilation failed'}finally{compile.disabled=!rights.checked}}
async function runGenerate(){if(!state.compiled||!state.compileInput)return;const item=selectedProvider();if(item&&item.credentialMode==='user_ephemeral'&&!byok.value){status.className='status error';status.textContent='Enter the selected Provider API key.';return}status.className='status';status.textContent='Submitting one confirmed call…';generate.disabled=true;const payload={compile:state.compileInput,planBinding:state.compiled.planBinding,confirmSingleCall:singleCall.checked,apiKey:byok.value};try{const pending=fetch('/api/generate',{method:'POST',headers:{'content-type':'application/json','x-playground-session':state.sessionId,'x-playground-client':'browser'},body:JSON.stringify(payload)});byok.value='';payload.apiKey='';const response=await pending;const value=await response.json();if(!response.ok)throw new Error(value.error||'Generation failed');badge.textContent='Generated';resultBody.replaceChildren();const pre=document.createElement('pre');pre.textContent=JSON.stringify(value.result,null,2);resultBody.append(pre);status.textContent='One call completed. Request images and credential were released.'}catch(error){badge.textContent='Blocked';status.className='status error';status.textContent=error instanceof Error?error.message:'Generation failed'}finally{byok.value='';invalidate()}}
document.querySelectorAll('[data-scenario]').forEach(button=>button.addEventListener('click',()=>{state.scenario=button.dataset.scenario;document.querySelectorAll('[data-scenario]').forEach(item=>item.setAttribute('aria-selected',item===button?'true':'false'));renderControls()}));rights.addEventListener('change',()=>{compile.disabled=!rights.checked;invalidate()});provider.addEventListener('change',renderProvider);composition.addEventListener('change',invalidate);compile.addEventListener('click',runCompile);generate.addEventListener('click',runGenerate);
Promise.all([fetch('/api/meta').then(response=>response.json()),fetch('/api/composition-presets').then(response=>response.json())]).then(([meta,catalog])=>{state.meta={...meta,presets:catalog.presets};renderMeta()}).catch(()=>{status.className='status error';status.textContent='Could not load Playground metadata.'})})();
</script></body></html>`
