export type JsonPrimitive = null | boolean | number | string
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue }
export type ProvenanceSource = 'user_explicit' | 'user_confirmed' | 'trusted_metadata' | 'reference_observed' | 'rule_inferred' | 'optimizer_suggested' | 'declared_default'
export interface Provenance { source: ProvenanceSource; sourceIds: string[]; createdBy: string; createdAt: string }
export interface ArtifactHandle { id:string; storeId:string; contentHash:string; mediaType:string; byteLength?:number; role:string; resolverId:string; availability:'available'|'deleted'|'expired'|'unknown'; retentionClass:string; retentionExpiresAt?:string; redactionPolicy:string }
export type EvidenceRegion = {kind:'rectangle';x:number;y:number;width:number;height:number}|{kind:'polygon';points:Array<{x:number;y:number}>}|{kind:'mask';maskArtifactId:string}
export interface Observation { id:string; contentHash:string; assetId:string; ontologyPath:string; value:unknown; confidence?:number; evidenceRegion?:EvidenceRegion; provenance:Provenance; analyzer?:{adapterId:string;model:string;promptVersion:string}; warnings:string[] }
export interface ObservationDecision { decisionId:string; decisionHash:string; observationId:string; observationHash:string; contextHash:string; status:'proposed'|'confirmed'|'rejected'; authority:'user'|'host_policy'|'trusted_metadata'|'auto_policy'; decidedBy:string; policyVersion?:string; decidedAt:string; reasonCode:string }
export interface SourceBinding { id:string; contentHash:string; targetPath:string; observationIds:string[]; relation:'preserve'|'reproduce'|'inspire'|'exclude'; priority:'hard'|'required'|'preferred' }
export interface BindingDecision { decisionId:string; decisionHash:string; bindingId:string; bindingHash:string; contextHash:string; status:'proposed'|'confirmed'|'rejected'; authority:'user'|'host_policy'|'trusted_metadata'|'auto_policy'; decidedBy:string; policyVersion?:string; decidedAt?:string; reasonCode:string }
export interface OntologyFact { path:string; value:unknown; provenance:Provenance; acceptedBy:string; sourceBindingIds:string[] }
export interface OntologyInstance { schemaVersion:string; facts:OntologyFact[]; unknownPaths:string[]; unresolvedItems:unknown[] }
export interface ScenarioPackRequest { packId:string; versionRange:string; configuration?:Record<string,JsonValue> }
export interface HostOverride { hostOverrideId:string; packId:string; overridePointId:string; operation:unknown; contentHash:string }
export interface HostPolicyOverlay { schemaVersion:string; caseId:string; caseRevision:number; overrides:HostOverride[]; overlayHash:string }
export interface ScenarioPackSelection { root:ScenarioPackRequest; extensions:ScenarioPackRequest[]; hostPolicyOverlay?:HostPolicyOverlay }
export interface OutputContract { artifactKind:'image'|'structured_review'|'layer_bundle'; dataType:'image'|'json'; mediaTypes:string[]; cardinality:{min:number;max:number}; dimensions?:{width:number;height:number}; background?:'transparent'|'opaque'|'any' }
export interface CaseSpec { id:string; revision:number; mode:'manual'|'assisted'|'auto'; scenario:ScenarioPackSelection; userIntent:string; assets:ArtifactHandle[]; trustedMetadata:unknown[]; policies:unknown; requestedOutput:OutputContract }
export interface VersionPin { id:string; version:string; digest:string }
export interface CompilationContext { caseSpecId:string; caseSpecRevision:number; caseSpecHash:string; artifactHashes:string[]; decisionHashes:string[]; scenarioCompositionLockHash:string; effectiveScenarioHash:string; rulePackPlugins:VersionPin[]; optimizer:VersionPin; contextHash:string }
export interface ScenarioPackManifest { schemaVersion:'voce.scenario-pack/v1alpha1'; packId:string; version:string; kind:'root'|'extension'; supportedInteractionModes:Array<'text_only'|'reference_guided'|'edit_existing'>; inputExpectations:unknown[]; outputExpectations:unknown[]; extensionOf?:{rootPackId:string;rootVersionRange:string}; license:string; provenance:unknown; coreRange:string; contractRanges:Record<string,string>; configurationSchema?:unknown; ui:unknown; dependencies:unknown[]; conflicts:unknown[]; composition:{before:string[];after:string[]}; contributions:Record<string,unknown[]>; fixtures:unknown[]; migrations:unknown[]; capabilityRequirements:unknown[]; declarations:{containsExecutableScenarioCode:false;distributionLifecycleScripts:false;containsExecutableFiles:false;fixturesRequireNetwork:false;fixturesRequireRealProvider:false;collectsTelemetry:false;mayHandlePersonImages:boolean;rightsDisclosureRequired:boolean}; permissions:{network:false;remoteCalls:false;secrets:false;filesystemWrite:false;mutateConfirmedFacts:false;authorizeCalls:false;overrideHostPolicy:false;selectProvider:false;changeBudgets:false}; distributionInventory:Array<{path:string;role:string;contentDigest:string}> }
export interface ScenarioCompositionLockEntry { packId:string;version:string;kind:'root'|'extension';manifestHash:string;packageDigest:string;configurationHash:string;resolvedDependencies:Array<{packId:string;version:string;packageDigest:string}>;contributionDigests:Record<string,string> }
export interface ScenarioCompositionLock { schemaVersion:'voce.scenario-pack-lock/v1alpha1'; contractVersion:'voce.scenario-pack/v1alpha1'; resolverVersion:string; catalogHash:string; canonicalization:'voce.canonical-json/v1alpha1'; rootPackId:string; entries:ScenarioCompositionLockEntry[]; compositionOrder:string[]; hostPolicyOverlayHash?:string; hostOverrideHashes:string[]; compositionHash:string; lockHash:string }
export interface EffectiveScenario { lockHash:string;rootPackId:string;extensionPackIds:string[];compositionOrder:string[];ontologyVocabulary:unknown[];rulePacks:unknown[];interpretationScopes:unknown[];promptSections:unknown[];reviewTemplates:unknown[];defaults:unknown[];capabilityRequirements:unknown[];declarations:unknown[];appliedOverrides:unknown[];effectiveScenarioHash:string }
export interface PackResolutionReport { status:'resolved'|'blocked';lockHash?:string;effectiveScenarioHash?:string;selected:unknown[];dependencyTrace:unknown[];compositionTrace:unknown[];overrideTraces:unknown[];conflicts:unknown[];warnings:unknown[];reportHash:string }
