import test from 'node:test'
import assert from 'node:assert/strict'
import { createScenarioPackRegistry, sha256, validateManifest } from './index.js'
import type { JsonObject, ScenarioPack, ScenarioPackManifest } from '@voce/contracts'

const emptyIndex = {ontologyVocabulary:[],rulePacks:[],interpretationScopes:[],promptSections:[],reviewTemplates:[],defaults:[],overridePoints:[]}
function manifest(packId:string, kind:'root'|'extension'='root', extra:Partial<ScenarioPackManifest>={}):ScenarioPackManifest {
  return {schemaVersion:'voce.scenario-pack/v1alpha1',packId,version:'1.0.0',kind,supportedInteractionModes:['text_only'],inputExpectations:[],outputExpectations:[],...(kind==='extension'?{extensionOf:{rootPackId:'first.party.root',rootVersionRange:'1.0.0'}}:{}),license:'Apache-2.0',provenance:{publisher:packId},coreRange:'*',contractRanges:{},ui:{defaultLocale:'en',locales:{en:{displayName:packId,description:'fixture',messages:{}}},disclosures:[],accessibility:{textAlternativesRequired:false,keyboardOperableReferenceUI:true,doesNotRelyOnColorAlone:true}},dependencies:[],conflicts:[],composition:{before:[],after:[]},contributions:emptyIndex,fixtures:[],migrations:[],capabilityRequirements:[],declarations:{containsExecutableScenarioCode:false,distributionLifecycleScripts:false,containsExecutableFiles:false,fixturesRequireNetwork:false,fixturesRequireRealProvider:false,collectsTelemetry:false,mayHandlePersonImages:false,rightsDisclosureRequired:false},permissions:{network:false,remoteCalls:false,secrets:false,filesystemWrite:false,mutateConfirmedFacts:false,authorizeCalls:false,overrideHostPolicy:false,selectProvider:false,changeBudgets:false},distributionInventory:[],...extra}
}
function pack(m:ScenarioPackManifest, overrides:JsonObject[]=[]):ScenarioPack {
  const points=overrides as any
  return {manifest:m,contributions:{ontologyVocabulary:[],rulePacks:[],interpretationScopes:[],promptSections:[],reviewTemplates:[],defaults:[],overridePoints:points,fixtureSuites:[]},migrations:[]}
}
function source(definition:ScenarioPack){return {kind:'memory' as const,definition,logicalFiles:[]}}

test('M1 manifest safety and canonical hashes remain available',()=>{validateManifest({schemaVersion:'voce.scenario-pack/v1alpha1',packId:'fixture.root',version:'0.1.0',kind:'root',declarations:{containsExecutableScenarioCode:false,distributionLifecycleScripts:false,containsExecutableFiles:false,fixturesRequireNetwork:false,fixturesRequireRealProvider:false},permissions:{network:false,remoteCalls:false,secrets:false,filesystemWrite:false,mutateConfirmedFacts:false,authorizeCalls:false,overrideHostPolicy:false,selectProvider:false,changeBudgets:false},distributionInventory:[]});assert.throws(()=>validateManifest({schemaVersion:'voce.scenario-pack/v1alpha1',packId:'x',version:'1.0.0',kind:'root',declarations:{containsExecutableScenarioCode:false,distributionLifecycleScripts:false,containsExecutableFiles:true,fixturesRequireNetwork:false,fixturesRequireRealProvider:false},permissions:{},distributionInventory:[]}),/PACK_DECLARATION_INVALID/)})

test('root-only and first-party/third-party fixtures use the same registry entrypoint',()=>{const registry=createScenarioPackRegistry();registry.register(source(pack(manifest('first.party.root'))));registry.register(source(pack(manifest('community.root'))));const first=registry.resolve({root:{packId:'first.party.root',versionRange:'1.0.0'},extensions:[]});const third=registry.resolve({root:{packId:'community.root',versionRange:'1.0.0'},extensions:[]});assert.equal(first.status,'resolved');assert.equal(third.status,'resolved');assert.equal(first.effectiveScenario.rootPackId,'first.party.root');assert.equal(third.effectiveScenario.rootPackId,'community.root')})

test('dependency and before/after edges produce stable order and hashes',()=>{const registry=createScenarioPackRegistry();const root=pack(manifest('first.party.root'));const a=pack({...manifest('ext.a','extension'),composition:{before:['ext.b'],after:[]}});const b=pack({...manifest('ext.b','extension'),dependencies:[{packId:'ext.a',versionRange:'1.0.0',role:'extension',reasonCode:'fixture'}]});registry.register(source(b));registry.register(source(root));registry.register(source(a));const selection={root:{packId:'first.party.root',versionRange:'1.0.0'},extensions:[{packId:'ext.b',versionRange:'1.0.0'}]};const one=registry.resolve(selection),two=registry.resolve(selection);assert.equal(one.status,'resolved');assert.equal(two.status,'resolved');assert.deepEqual(one.lock.compositionOrder,['first.party.root@1.0.0','ext.a@1.0.0','ext.b@1.0.0']);assert.deepEqual(one.lock,two.lock);assert.deepEqual(one.effectiveScenario,two.effectiveScenario);assert.deepEqual(one.report,two.report)})

test('catalog insertion order does not change semantic result',()=>{const a=pack(manifest('first.party.root')),b=pack({...manifest('ext.b','extension'),composition:{before:[],after:[]}});const r1=createScenarioPackRegistry(),r2=createScenarioPackRegistry();r1.register(source(a));r1.register(source(b));r2.register(source(b));r2.register(source(a));const s={root:{packId:'first.party.root',versionRange:'1.0.0'},extensions:[{packId:'ext.b',versionRange:'1.0.0'}]};const x=r1.resolve(s),y=r2.resolve(s);assert.equal(x.status,'resolved');assert.equal(y.status,'resolved');assert.equal(x.lock.lockHash,y.lock.lockHash);assert.equal(x.effectiveScenario.effectiveScenarioHash,y.effectiveScenario.effectiveScenarioHash)})

test('missing dependency, incompatible extension, explicit conflict, and cycles block',()=>{const r=createScenarioPackRegistry();const root=pack(manifest('first.party.root'));r.register(source(root));const missing=pack({...manifest('ext.missing','extension'),dependencies:[{packId:'absent',versionRange:'1.0.0',role:'extension',reasonCode:'fixture'}]});r.register(source(missing));let result=r.resolve({root:{packId:'first.party.root',versionRange:'1.0.0'},extensions:[{packId:'ext.missing',versionRange:'1.0.0'}]});assert.equal(result.status,'blocked');assert.ok(result.report.conflicts.some(c=>c.code==='PACK_DEPENDENCY_MISSING'));const wrong=pack({...manifest('ext.wrong','extension'),extensionOf:{rootPackId:'other.root',rootVersionRange:'1.0.0'}});r.register(source(wrong));result=r.resolve({root:{packId:'first.party.root',versionRange:'1.0.0'},extensions:[{packId:'ext.wrong',versionRange:'1.0.0'}]});assert.equal(result.status,'blocked');assert.ok(result.report.conflicts.some(c=>c.code==='PACK_COMPATIBILITY_MISMATCH'));const c1=pack({...manifest('ext.c1','extension'),composition:{before:['ext.c2'],after:[]}}),c2=pack({...manifest('ext.c2','extension'),composition:{before:['ext.c1'],after:[]}});r.register(source(c1));r.register(source(c2));result=r.resolve({root:{packId:'first.party.root',versionRange:'1.0.0'},extensions:[{packId:'ext.c1',versionRange:'1.0.0'},{packId:'ext.c2',versionRange:'1.0.0'}]});assert.equal(result.status,'blocked');assert.ok(result.report.conflicts.some(c=>c.code==='PACK_ORDER_CYCLE'))})

 test('declared HostOverride is accepted and undeclared override is blocked',()=>{const pointBase={id:'theme',targetKind:'configuration',targetPath:'theme',allowDisable:false,maximumImportance:'preferred'};const point={...pointBase,contentDigest:sha256(pointBase)};const m=manifest('first.party.root','root',{contributions:{...emptyIndex,overridePoints:[{id:'theme',schemaVersion:'voce.override-point/v1alpha1',contentDigest:point.contentDigest}]}});const r=createScenarioPackRegistry();r.register(source(pack(m,[point as any])));const overlay={id:'overlay',caseId:'case-1',caseRevision:1,authority:'host_policy' as const,reasonCode:'fixture',overrides:[{id:'o1',operation:{kind:'set_configuration' as const,packId:'first.party.root',overridePointId:'theme',value:'dark'},reasonCode:'fixture',contentHash:'sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'}],overlayHash:'sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'};let result=r.resolve({root:{packId:'first.party.root',versionRange:'1.0.0'},extensions:[],hostPolicyOverlay:overlay});assert.equal(result.status,'resolved');assert.equal(result.effectiveScenario.appliedOverrides.length,1);result=r.resolve({root:{packId:'first.party.root',versionRange:'1.0.0'},extensions:[],hostPolicyOverlay:{...overlay,overrides:[{...overlay.overrides[0],operation:{...overlay.overrides[0].operation,overridePointId:'missing'}}]}});assert.equal(result.status,'blocked');assert.equal(result.report.conflicts[0].code,'PACK_OVERRIDE_POINT_NOT_FOUND')})

test('duplicate packId/version with a different digest is rejected',()=>{const r=createScenarioPackRegistry();r.register(source(pack(manifest('same'))));assert.throws(()=>r.register(source(pack({...manifest('same'),provenance:{publisher:'different'}}))),/PACK_DUPLICATE_ID_VERSION/)})
